sonar.organization=diamondstalkeresposos
sonar.projectKey=diamondstalkeresposos
sonar.projectName=Mesesaurios
sonar.projectVersion=2.0.1

# Fuentes a analizar
sonar.sources=src
sonar.exclusions=**/*.test.js,**/*.spec.js,**/node_modules/**,**/build/**

# Encoding
sonar.sourceEncoding=UTF-8

# Excluir coverage — no tenemos tests implementados
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
